spring:
  rabbitmq:
    host: localhost
    port: 5672
  cloud:
    openfeign:
      circuitbreaker:
        enabled: false
    discovery:
      enabled: false

eureka:
  client:
    enabled: false

JWT_SECRET: dGVzdC1zZWNyZXQta2V5LWZvci1nYXRlcGF5LWp3dC10ZXN0aW5nLW9ubHk=
JWT_EXPIRATION: 900000
JWT_REFRESH_EXPIRATION: 86400000